source 'https://rubygems.org'

group :default do
  gem 'ancestry'
  gem 'babosa'
  gem 'coffee-rails'
  gem 'configliere'
  gem 'devise'
  gem 'devise-russian'
  gem 'enumerize'
  gem 'friendly_id', '~> 5.1.0'
  gem 'jbuilder'
  gem 'jquery-rails'
  gem 'omniauth-facebook'
  gem 'omniauth-google-oauth2'
  gem 'omniauth-mailru',            :git => 'git://github.com/semenyukdmitriy/omniauth-mailru', :ref => 'fbf40e8'
  gem 'omniauth-odnoklassniki'
  gem 'omniauth-twitter'
  gem 'omniauth-vkontakte',         '~> 1.3'
  gem 'omniauth-yandex'
  gem 'paperclip'
  gem 'paperclip-elvfs'
  gem 'pg'
  gem 'progress_bar'
  gem 'rails'
  gem 'sass-rails'
  gem 'simple_form'
  gem 'uglifier'
  gem 'jquery-fileupload-rails'
end

group :development, :test do
  gem 'annotate'
  gem 'brakeman'
  gem 'hirb'
  gem 'rspec-rails'
end
